### ISSUE TITLE
Features should be grouped by extraction method

### ISSUE THREAD

**Issue by smacker** [src-d/code-annotation#106]
You can see it on wireframes, but we don't have information about those groups and how to assign features to them. So currently all features go to one tab.

**Comment by dpordomingo** [comment]
As agreed during Team Focus Meeting 2018-03-07, the table used to display the extracted features won't be changed.
If it is needed any change, it will be displayed the raw data sent by the Feature-Extractor REST API

Feel free to reopen if there is any news/updates about this decision
