### ISSUE TITLE
Annotation: some files are too wide and break the UI

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#107]
Some file pars like https://code-annotation-staging.srcd.run/exp/1/16 are too wide

<img width="1285" alt="screen shot 2018-02-14 at 6 29 22 pm" src="https://user-images.githubusercontent.com/5582506/36218723-9fe82632-11b5-11e8-911f-478d81ad3568.png">

This issue is about finding a way of displaying such files better.

**Comment by ricardobaeta** [comment]
Horizontal scroll with visual hint, only when this happens. Makes sense?
