### ISSUE TITLE
Logs dissapeared

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#109]
After merging https://github.com/src-d/code-annotation/pull/102 and deploying into staging the logs disappeared.

I just reverted acf8653 and it worked.

**Comment by smacker** [comment]
what do you mean disappeared? If there is no warning or errors there shouldn't be any logs. That was the issue and PR.

**Comment by dpordomingo** [comment]
but we should keep the access log...

**Comment by smacker** [comment]
it's kind of opposide to what was requested by @bzz
 
btw I'm sure you can find access log in google cloud.
but we can write 2 different logs as nginx does, if it's really necessary. (I don't really think so because usually you have another place for access logs in production)

**Comment by dpordomingo** [comment]
for sure there can be a lot of ways to access the logs... but till we have no alternative to GCP, we should keep the info...

**Comment by smacker** [comment]
I don't have access to GCP. But according to documentation you should be able to see http requests logs: https://cloud.google.com/compute/docs/load-balancing/http/#logging

> What is logged
> HTTP(S) load balancing log entries contain information useful for monitoring and debugging your HTTP(S) traffic. Log entries contain the following types of information:
> 
> - General information shown in most GCP logs, such as severity, project ID, project number, timestamp, and so on.
> - HttpRequest log fields.
> - a statusDetails field inside the structPayload. This field holds a string that explains why the load balancer returned the HTTP status that it did. The tables below contain further explanations of these log strings.

**Comment by bzz** [comment]
May be related to https://github.com/src-d/code-annotation/issues/96 ? 

Do not know yet how GCP is setup for this deployment, but we should indeed separate the access logs captured by infrastructure like load balancer and a meaningful app logs.

**Comment by bzz** [comment]
As discussed \w @dpordomingo in this issue we need to:

 - Make sure, right log-level is used though the app
 - Make sure it's in format, understood by https://console.cloud.google.com/logs/viewer (so it's possible to sort by level)
 - Make sure log level is configurable per deployement
 - Make suer there are no access logs (GET/PUT, etc) in the app logs on staging/prod envs

Do you think this can be transferred in TODO list in RP readme?

**Comment by dpordomingo** [comment]
logging specs were described by https://github.com/src-d/code-annotation/issues/123
We'll track that development in the new issue
