### ISSUE TITLE
Documents are truncated

### ISSUE THREAD

**Issue by r0mainK** [src-d/code-annotation#112]
In the case of the second file below there are not many changes, but the file seems truncated from lines 17 to 89/99 so it's hard to tell whether the file is similar (e.g. if the file is 1000 lines long) or different (e.g. if it's 100). 

<img width="1207" alt="screen shot 2018-02-15 at 10 06 32 1" src="https://user-images.githubusercontent.com/32878976/36248584-5009afb8-1238-11e8-8a31-84fe79282dc6.png">

**Comment by bzz** [comment]
Thank you for the feedback!

I'm not sure I understand 
> the file seems truncated from lines 17 to 89/99

could you please elaborate on this a bit?

**Comment by r0mainK** [comment]
Sure, well on the left of the code you can see the line number start at 17, but I cannot scroll up to see the first 16 lines. Also since on lines 89 and 99 there is an `@Override` I guess there is a function below but I canno't scroll down to see it. That's a problem because even if the files are the same below and under, the length of the document will impact on whether the file is categorized as different or similar.

**Comment by bzz** [comment]
Got it, thank you for explaining @r0mainK !

@smacker @carlosms how much work do you guys think it would be to switch from a diff rending \w `@@ -19,106 +15,106 @@` to full file only with the color highlight for diffs?

**Comment by smacker** [comment]
Most probably we just need to change `Context` value of `UnifiedDiff`. Now it's 3. If we put a really big number there it should work. Not the most pretty way to solve the issue, but the easiest one.
The only problem - we store diffs in DB, so the change won't appear on staging after deployment.

**Comment by EgorBu** [comment]
Hi,
another good thing that may help - possibility to switch on/off highlights and diff so we can see full contents of files.
In some cases, highlights/diff are misleading (ex: https://github.com/src-d/code-annotation/issues/174 & #113 ).
Why it may help - if a diff is wrong you may need to scroll a lot to see the beginning of "new" part of the code - it's quite inconvenient.

**Comment by EgorBu** [comment]
Another example why full content can be useful is pair 325, it's hard to understand what was modified

**Comment by smacker** [comment]
I return issue in backlog. Some improvements were done in #194 but it doesn't solve the issue completely. Let's see how it works and decide what to do later.

**Comment by bzz** [comment]
As soon as it has been addressed and there is no more feedback, closing it for now.

Please feel free to reopen it if this would still be an issue at any time later on.
