### ISSUE TITLE
Difference detected even though files are the same

### ISSUE THREAD

**Issue by r0mainK** [src-d/code-annotation#113]
In the sixth documents all visible lines are exactly the same, but the tool seems to think the contrary:

<img width="1280" alt="screen shot 2018-02-15 at 10 12 26" src="https://user-images.githubusercontent.com/32878976/36248797-ebebbfde-1238-11e8-8333-79048fc1b421.png">

<img width="1280" alt="screen shot 2018-02-15 at 10 14 36" src="https://user-images.githubusercontent.com/32878976/36248839-1497b370-1239-11e8-93cd-6582c1232d72.png">

**Comment by dpordomingo** [comment]
Since there is a new issue having more details about this problem, I'll close and mark this one as duplicated of https://github.com/src-d/code-annotation/issues/174
Thanks for reporting it @r0mainK ; we can follow the discussion over there
