### ISSUE TITLE
Stop using the odd `.env.tpl` file

### ISSUE THREAD

**Issue by mcuadros** [src-d/code-annotation#120]
As explained here:
https://github.com/src-d/code-annotation/pull/36#discussion_r167946866

The usage of env file, populated with empty env vars is odd, and not very Devops friendly since handly configuration files is a something to be avoided, even if it contains env vars.

The env vars should be explicitly defined in all the examples, and be omitted if contains the default value or are empty, in the same that this should be explicitly defined in the `.travis.yml.

**Comment by smacker** [comment]
I believe we don't use `.env` file anywhere besides local dev. Travis, k8s, drone all have defined variables in yml files.

**Comment by mcuadros** [comment]
Its explained as the default method to keep the variable in the README.md

**Comment by smacker** [comment]
that must be fixed!

**Comment by dpordomingo** [comment]
(@bzz as you explained to me I moved this issue to backlog after adding to the project)
