### ISSUE TITLE
Add prefix for config variables

### ISSUE THREAD

**Issue by smacker** [src-d/code-annotation#121]
We have prefixes for oauth&jwt but we also need a prefix for main variables like `host`,`port` and so on.

Prefix to be used: `CAT_` (Code Annotation Tool)

**Comment by bzz** [comment]
What prefixes do you propose to use?

**Comment by smacker** [comment]
normally it's the name of an application.

**Comment by dpordomingo** [comment]
Are `OAUTH_`, `JWT_`, `DB_` proper preffixes?
I'd purpose `CA_`,  `CAT_`, `SCAT_`, `CODE_ANNOTATION_` for prefixing all our env vars...

**Comment by smacker** [comment]
absolutely correct. We need to add app prefix to them too. Thanks for pointing!

**Comment by dpordomingo** [comment]
I updated the issue desc according to the agreed prefix (via Slack): `CAT_`
