### ISSUE TITLE
Question: Similarity of "non-code" (comment) file parts

### ISSUE THREAD

**Issue by marnovo** [src-d/code-annotation#126]
When running the code annotation for the first time, I noticed that the diff was highlighting the difference in commented parts of the code file. The actual (non-comment) code from the file was seemingly identical. I have provided a screenshot below.

This could make some people mark this file as similar (since they see diffs in the comments), while others market it as identical (since the code is the same).

Since I guess commented parts wouldn't matter (correct me if wrong on this), what is the intended behavior of the user? @vmarkovtsev 

Depending on the answer, this could bias users in an unintended way given the interface (at least without explicit instructions otherwise), and becomes a bug—otherwise, it's a feature. :)

<img width="1680" alt="screen shot 2018-02-15 at 6 47 24 pm" src="https://user-images.githubusercontent.com/15906764/36280519-a76b160e-1281-11e8-8368-303a5c35d7e5.png">

**Comment by bzz** [comment]
Great catch! There are many cases in this particular dataset, where the diff algorithm reports changes of the whole file, and many times it's just a single whitespace added in the middle.

~@r0mainK or @warenlg might have a list of those somewhere already.~ A simpler case of this (but not for comments) has been reported under https://github.com/src-d/code-annotation/issues/113

From my understanding, indeed, by showing the diff we may bias the user BUT not showing it make annotations VERY hard. That was something discussed \w @vmarkovtsev at the beginning of the project. 

It's also a great case, proving why we do need this research - a well-known diff algorithm library that is used reports huge difference, but a human will, as you just did notice and report that the files are identical.

**Comment by warenlg** [comment]
This is not obvious to me, when annotating the dataset, I personally care about comments otherwise you would mark the following pair as different whereas they are totally duplicated to me:
![same_commented](https://user-images.githubusercontent.com/24694845/36307852-60922f90-131e-11e8-8ad8-4244de702f76.png)

**Comment by dpordomingo** [comment]
This question seemed to be answered by Alex and Waren.
If the provided answers do not answer your question, feel free to reopen or create a new issue with a feature request.
