### ISSUE TITLE
Sequential progress of the dataset 

### ISSUE THREAD

**Issue by warenlg** [src-d/code-annotation#131]
Quick example:
I already annotated the first 500 pieces of code, and now that I have a better understanding of the task and its requirements, I want to do the first 100 pieces again. However, each time I annotate one of these first 100 pieces, the piece of code that comes next is the first that has not been done yet that is to say the 501st, and I have to scroll everything down again.

What do you think about letting a sequential progress? So that whatever if the piece of code **i** is already annotated or not, the next one coming after annotating it would be the **i+1**th.

It is more a feature but that would be useful for @r0mainK also

**Comment by r0mainK** [comment]
I agree it would be better this way, it would not change how you use the tool during a first pass but would be much easier afterwards. I think that not only the speed but the way you annotate files changes a lot between the first dozen or hundred files, but not so much afterwards, which means you probably make "mistakes" relative to how you annotate early on, and that is problematic if we want the data to be as coherent as possible.
