### ISSUE TITLE
Add simple analytics

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#140]
To be able to grow this project UX based on it's actual usage a designer would need to have access to some data.

This issue includes:
 - enable Google Analytics conditionally (dev env should not have one, staging deployment should have one, production would have different one) 
 - as a start, only emit [PageView events](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications) for every URL change in our FE

**Comment by ricardobaeta** [comment]
It would be great to know which UI element triggered the URL change.

**Comment by dpordomingo** [comment]
Yes @ricardobaeta it makes sense and is doable, but I think it should be tracked it in a separated issue, so if @bzz agree, I'd suggest you open a new one.

**Comment by bzz** [comment]
Analytics was added, subsequent work will be done in separate PRs.
