### ISSUE TITLE
Add multiple experiments support

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#149]
There is going to be 1 more dataset to label coming soon, of 500 more file pairs.

To prepare for it, we need to:

 - [x] add frontend experiment list page (without real data)
 - [x] make sure backend (api) works correctly with more than 1 experiment (we *might* have something hardcoded)
 - [x] add support for multiple experiments on frontend side (many places assume only one or have hardcoded value now)
 - [x] update importing tools, so the data from [sqlite format](https://github.com/src-d/code-annotation/blob/master/cli/import/examples/example.sql) works for multiple experiments as expected (currently, there is hardcoded experiment 1)

**Comment by smacker** [comment]
done!
