### ISSUE TITLE
Release process: publish more artefacts

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#159]
As part of release process, we need to add publishing:
 - [x] binary artefact to the GH release (at least linux, other platforms #184)
 - [ ] docker image \w appropriate version number to https://hub.docker.com/r/srcd/code-annotation/

artefacts.

**Comment by smacker** [comment]
Why only Linux? It works fine on macOS too.

**Comment by dpordomingo** [comment]
Binaries should be pushed by https://github.com/src-d/code-annotation/pull/130
I reviewed the drone config and I realized that it was not listening for tags. I just enabled the tag hook.
I'll release a v0.0.2 on Monday and confirm if it worked

**Comment by bzz** [comment]
> Why only Linux? It works fine on macOS too.

Makes sense, updated PR description. 
Everything beyond our current production env which is on linux is a `nice to have` at this stage though.

**Comment by dpordomingo** [comment]
Linux binaries were pushed to the [`v0.0.2` release](https://github.com/src-d/code-annotation/releases/tag/v0.0.2)

what's next?
- [x] ensure the version is properly used in the artifact name (it was not available in drone)
- [ ] confirm if macOS binary can be generated and pushed too, and do it if so
- [x] analyze docker image requirement

**Comment by dpordomingo** [comment]
@bzz docker image is already available at https://hub.docker.com/r/srcd/code-annotation/tags/

![image](https://user-images.githubusercontent.com/2437584/36695018-4dad50c4-1b40-11e8-9608-4bd7567eaf5f.png)

If we'd use prod env the docker image tag would be the git tag; since we're using staging env, the docker image tag is defined by the commit hash.

![image](https://user-images.githubusercontent.com/2437584/36695152-b7b2c67a-1b40-11e8-8e77-90d7275197f3.png)

**Comment by carlosms** [comment]
Here ~~https://github.com/src-d/ci/pull/57~~ https://github.com/src-d/ci/pull/58 is my attempt to fix
> ensure the version is properly used in the artifact name (it was not available in drone)

**Comment by bzz** [comment]
Nice!

I belive @dpordomingo also might want to close this issue (as both, binaries and docker are available in 0.0.2) and open a new separate ones, about docker artifact naming and a binaries for other platforms.

**Comment by smacker** [comment]
I would suggest to use Travis for release images/binaries as we do in other projects. And keep drone only for deployment.

**Comment by dpordomingo** [comment]
we're already using drone.io for pushing docker images, so for reusability, we can use it for delivering the release artifacts too.
If so, this issue would be solved by https://github.com/src-d/code-annotation/pull/183

**Comment by bzz** [comment]
I belive #183 addresses the need and will resolve this issue.

At the same time, I agree, we should be using Travis for CI and Drone for CD consistently, so https://github.com/src-d/code-annotation/issues/185 has been created.

PR description updated to reflect the scope.
