### ISSUE TITLE
Configure the GA_TRACKING_ID for Google Analytics

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#169]
In order to enable Google Analytics in Code Annotation tool as required by https://github.com/src-d/code-annotation/issues/140 we need to configure a `GA_TRACKING_ID` in the helm charts, but this `GA_TRACKING_ID` should be provided in advance by Product

**Comment by dpordomingo** [comment]
I'm not sure if @marnovo or @bzz could provide the `GA_TRACKING_ID` that should be used for Code Annotation tool

**Comment by bzz** [comment]
I do not have access to GA, so the person who takes this need to ping @marnovo and ask to create ned profile and send a tracking code.

**Comment by marnovo** [comment]
@gomesfernanda will create the `GA_TRACKING_ID` for the hosted annotation tool and provide it privately (I guess it's probably not a good idea to share it here?).

**Comment by dpordomingo** [comment]
That code will be published in the app source code, but ok: private will work for me :D

**Comment by bzz** [comment]
@marnovo thank you for quick response!

@gomesfernanda it's totally fine to post it here as well, as it's going to be in plain text at every HTML page of the web-app.

**Comment by gomesfernanda** [comment]
GA Tracking ID for Code Annotation Tool: UA-109494282-2

**Comment by dpordomingo** [comment]
Many thanks @gomesfernanda 
The data will be available at GA panel once https://github.com/src-d/code-annotation/pull/202 has been merged, and deployed into staging _aka_ prod

**Comment by dpordomingo** [comment]
PR was merged but not yet deployed. I'll notify here once it has been deployed and data is send to GA

**Comment by dpordomingo** [comment]
[CAT v0.0.4 was released](https://github.com/src-d/code-annotation/releases/tag/v0.0.4)
You should start receiving data in GA panel.

**Comment by gomesfernanda** [comment]
Weirdly, I'm not receiving traffic. I've been checking since the morning. Just now we have a notification on GA tab saying
"Missing Tracking Code error
Page https://code-annotation-staging.srcd.run/ for property Code annotation tool is missing valid tracking code."

I checked the source code of code annotation tool page and the Tracking ID is correct. @dpordomingo maybe you can assist on this? Thanks!

**Comment by smacker** [comment]
Incorrect copy-past: https://github.com/src-d/code-annotation/pull/209 🤦‍♀️

**Comment by gomesfernanda** [comment]
@smacker @dpordomingo Analytics not tracking visits yet.

I had clicked "check again" on the GA notification for "missing tracking code", but it appeared again for me this afternoon.

> "Missing Tracking Code error
> Page https://code-annotation-staging.srcd.run/ for property Code annotation tool is missing valid tracking code."

**Comment by dpordomingo** [comment]
Sorry for the misunderstanding @gomesfernanda :
What @smacker did, was to pull-request the fix, but not yet integrate and deploy it.

I just reviewed and accepted the PR https://github.com/src-d/code-annotation/pull/209 ; I also released and deployed [CAT v0.0.5](https://github.com/src-d/code-annotation/releases/tag/v0.0.5) that should fix that problem with `GA_TRACKING ID`; data should now be sent to GA panel,

could you confirm it?

![image](https://user-images.githubusercontent.com/2437584/37203427-e01b92b8-238d-11e8-8738-d92722f26ece.png)

**Comment by dpordomingo** [comment]
@gomesfernanda feel free to reopen the issue if there is there is no data in GA panel ;)

**Comment by gomesfernanda** [comment]
It's working now! Just checked. Thanks, guys!!!! :)
