### ISSUE TITLE
Documentation: make it awesome

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#17]
Add:
 - awesome README based on [this guide](https://github.com/src-d/guide/blob/master/engineering/documentation.md), and [fill placeholders](https://github.com/src-d/code-annotation/pull/12#pullrequestreview-89816444)
 - [DCO](https://github.com/src-d/guide/blob/master/engineering/licensing.md#developer-certificate-of-origin) 
 - DCO sign-off-checker
 -

**Comment by smacker** [comment]
@bzz I don't have access to project settings to add `DCO sign-off-checker`
