### ISSUE TITLE
Experience Design on Code Annotation Status

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/code-annotation#171]
@bzz @smacker @dpordomingo @carlosms 

Would you please be so kind to tell me what is in your opinion the priority given on the details bellow?

https://github.com/src-d/code-annotation/issues/55
https://github.com/src-d/code-annotation/issues/54
https://github.com/src-d/code-annotation/issues/167
https://github.com/src-d/code-annotation/pull/155#issuecomment-368537467

**Comment by bzz** [comment]
Thank you for the questions - I think it's better to discuss each item in the appropriate issues from here.

About a priority - it's hard to tell, as it's a live thing, determined by team capacity at any given moment and can be see on individual [team Kanban boards](https://github.com/src-d/guide/blob/master/engineering/methodology.md#team-kanban).

As noted in https://github.com/src-d/code-annotation/pull/155#issuecomment-369233340 - we might want to have a new issue for the last element from PR description.

Just FYI - I realize it might not be documented, but we generally tend not to use project issue tracker for discussions very much (those usually happen in IM channels) and reserver it for more actionable/scoped items, thus not much action in here, and a smaller issues are preferred to umbrella ones.

Will be closing this one, but please feel free to re-open in case you feel something is missing or i.e other communication channels do not work, etc.
