### ISSUE TITLE
Default env var for CAT_DB_CONNECTION does not work out of the box

### ISSUE THREAD

**Issue by carlosms** [src-d/code-annotation#173]
From a comment made by @smacker in PR https://github.com/src-d/code-annotation/pull/170#discussion_r170672733

> Opening `/var/code-annotation/internal.db` will fail with error: directory doesn't exist.
> 
> We have 3 options:
> - change defaults
> - change documentation
> - add `mkdir` in Dockerfile (I prefer this one)

**Comment by dpordomingo** [comment]
`mkdir` suits for me too

**Comment by carlosms** [comment]
2 votes for mkdir, and it's also fine for me, so let's go with that option.
