### ISSUE TITLE
Show new lines, tabs, whitespaces

### ISSUE THREAD

**Issue by EgorBu** [src-d/code-annotation#176]
Hi,
it may help to understand why diff behaves not so obvious in some cases (https://github.com/src-d/code-annotation/issues/174 + pair 29)

**Comment by bzz** [comment]
@ricardobaeta we are talking about triggering an optional mode of the text editors, that shows non-printable characters, something like ![editor example](http://netbeans.dzone.com/sites/all/files/show-spaces-1.png)

Could you please think about it and provide a screenshot, that have the control element for this action placed somewhere in the annotator UI? I would imagine that a checkbox might be a good fit as it represents the state.

@smacker AFAIK we are using https://github.com/rtfpessoa/diff2html to display the diff - could you please provide some estimates on how much would would it be, to enable this behavior for the components displaying the text?

**Comment by smacker** [comment]
@bzz maybe we shouldn't touch diff2html. According to the issue title we can just preprocess diffs, replacing characters.

**Comment by smacker** [comment]
I changed the title of the issue removing `etc` from it. So it's feasible to implement now.
If we need to show any other characters please update issue or create a new one.

**Comment by ricardobaeta** [comment]
@bzz @smacker I'm a bit lost here. Is this moving forward now? Wireframing I mean.

**Comment by smacker** [comment]
@ricardobaeta I'm starting implementation now. It would be cool to have control somewhere to switch off/on this feature. But for diff itself, we can start with the simplest approach (don't change anything, just replace symbols).

**Comment by smacker** [comment]
Example of spaces and new lines:
<img width="1200" alt="screen shot 2018-03-02 at 17 41 47" src="https://user-images.githubusercontent.com/406916/36910445-1348a308-1e41-11e8-8d5c-ce41d93b9f78.png">

Example of tabs to spaces (my branch vs staging):
<img width="1201" alt="screen shot 2018-03-02 at 17 40 49" src="https://user-images.githubusercontent.com/406916/36910480-24587f56-1e41-11e8-98ec-c2cf89a7a239.png">
<img width="1200" alt="screen shot 2018-03-02 at 17 40 59" src="https://user-images.githubusercontent.com/406916/36910483-286858fa-1e41-11e8-9252-23a69a181995.png">

I need a switcher to continue.

**Comment by ricardobaeta** [comment]
@smacker I'm working on the wireframe, thanks for the notice :)

**Comment by ricardobaeta** [comment]
@smacker @bzz @dpordomingo @carlosms

Here's the wireframe for this toggler (it affects both files). It's placed on a block, previously designed for pair files custom visualization.

<img width="1141" alt="screen shot 2018-03-07 at 10 25 18" src="https://user-images.githubusercontent.com/1746146/37087331-e55abc2e-21f1-11e8-98fd-cc5e6df4883d.png">

**Comment by dpordomingo** [comment]
@smacker whenever you close this issue, please leave an update in related https://github.com/src-d/code-annotation/issues/174; thanks

**Comment by dpordomingo** [comment]
I wonder if this could be considered when solving https://github.com/src-d/code-annotation/issues/196
