### ISSUE TITLE
UI suggestions. Progress bar 

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/code-annotation#18]
Here is the feedback on the current UI:

1. Awesome!
2. [ ] I suggest placing the progressbar at the top, inline with the header to save the precious vertical space.
3. [x] Is there a way to make the two pages scroll together? Or at least jump at the same line by clicking?
4. [x] GitHub sign in belongs to @smacker always...

**Comment by smacker** [comment]
1. Thanks!
2. @ricardobaeta 
3. We will implement it for sure, but we need @ricardobaeta because sometimes you may want to scroll together and sometimes not.
4. There is no backend at all yet :-D

**Comment by ricardobaeta** [comment]
@vmarkovtsev Thank you :)

> I suggest placing the progressbar at the top, inline with the header to save the precious vertical space.

I'm actually sketching in my mind a **combination/blend** of the **main actionable elements** with the **progress bar** == minus one horizontal block

**Comment by dpordomingo** [comment]
@vmarkovtsev @ricardobaeta Are you talking about this kind of progress bar?

![image](https://user-images.githubusercontent.com/2437584/35147185-fa9c17f8-fd0d-11e7-9ef1-1bcbc41dfc62.png)

**Comment by vmarkovtsev** [comment]
Can be under, can be inline... I am fine with both.

**Comment by bzz** [comment]
@ricardobaeta do you think you could post a screenshots/wireframe \with suggestion how this could look like?

**Comment by ricardobaeta** [comment]
@bzz The collapsible Header would be something like this https://github.com/src-d/code-annotation/issues/54#issuecomment-369202612

**Comment by bzz** [comment]
Very nice! I'm about to close this one in favor or more specific #54 .


@vmarkovtsev please feel free to re-open this, or file a new issue if that does not address the need!
