### ISSUE TITLE
Receive and store serialized ProtoBuf \w UAST as part of the input

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#197]
Right now, the [schema of sqlite input](https://github.com/src-d/code-annotation/blob/master/cli/import/examples/example.sql#L7) includes content of the 2 files and a git metadata.

After discussion \w @vmarkovtsev we determined the need to (optionally) add serialized UASTs of both files to that, which are going to be sent to the reviewer REST API for feature extraction.

This is crucial in order to enable upcoming function-level annotations.

**Comment by dpordomingo** [comment]
As talked irl with @bzz UAST will be an optional field in input data
