### ISSUE TITLE
Update GitHub OAuth callback when Auth PR is merged

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#201]
Once the [PR refactoring Authentication](https://github.com/src-d/code-annotation/pull/142) is merged and deployed, the GitHub OAuth callback must be changed to
`https://code-annotation-staging.srcd.run/auth`

The callback change and the release MUST be coordinated:
- The release must not be done till the person in charge of changing it is ready to proceed.
- The OAuth callback must not be changed till the release has been deployed.

**Comment by dpordomingo** [comment]
@bzz can you change it whenever we need it? or should we ask any other person?

**Comment by bzz** [comment]
@dpordomingo This can be done only by GH org admin :/

Before asking anybody for this, could you please remind what is the problem we are trying to solve by URL change?  I'm trying to understand why `/oauth-callback`string  would not work any more for this application.

**Comment by dpordomingo** [comment]
I just followed @smacker recommendations. I understand that `/auth` is more clean from the user perspective, but I can change it if you see technical or organizative problems.

**Comment by bzz** [comment]
To be honest, although I agree, name would become a bit confusing that way, I think it would be much easier to keep an old URL for now in #142

**Comment by dpordomingo** [comment]
given the prev comment, this requirement won't be done
