### ISSUE TITLE
Create and communicate the new GA_TRACKING_ID for testing purposes

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#216]
As required by [Prepare and deploy Production environment #215](https://github.com/src-d/code-annotation/issues/215) it is needed to create a new `GA_TRACKING_ID` to be used for testing purposes.

The current `GA_TRACKING_ID` (`UA-109494282-2`) will be kept as Production one, so Production data won't be polluted with testing events.

When the process will finish, it should be:
- Prod
  - tracking id: `UA-109494282-2`
  - url: ~~http://code-annotation-staging.srcd.run~~ &rarr; http://code-annotation.sourced.tech
- Staging: 
  - tracking id: `UA-115770171-1`
  - url: http://code-annotation-staging.srcd.run

Since the migration Staging &rarr; Production will be done separately, do not change current tracking URL; we'll ping you when we're ready for the migration.

The new code for testing purposes can be communicated here :point_down:

**Comment by dpordomingo** [comment]
As talked irl with @gomesfernanda , I updated the issue desc with this info:

When the process will finish, it should be:
- Prod
  - tracking id: `UA-109494282-2`
  - url: ~~http://code-annotation-staging.srcd.run~~ &rarr; http://code-annotation.sourced.tech
- Staging: 
  - tracking id: `UA-115770171-1`
  - url: http://code-annotation-staging.srcd.run

Since the migration Staging &rarr; Production will be done separately, do not change current tracking URL; we'll ping you when we're ready for the migration.

**Comment by gomesfernanda** [comment]
GA Tracking ID created for Staging (Testing) environment. So what we have is:

- Production
	- Tracking ID: `UA-109494282-2`
	- **Current** URL: https://code-annotation-staging.srcd.run/ (_to be migrated_)
	- **Future** URL: http://code-annotation.sourced.tech


- Staging
	- Tracking ID: `UA-115770171-1`
	- URL: https://code-annotation-staging.srcd.run/

Meaning, for now Staging and Production IDs will track same data (same URL). As soon as @dpordomingo pings me, I'll change Prod URL and we'll see different data.

**Comment by dpordomingo** [comment]
Many thanks!
We'll communicate you when we're ready to migrate
