### ISSUE TITLE
Create a new GitHub OAuth App for Prod env

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#217]
As required by [Prepare and deploy Production environment #215](https://github.com/src-d/code-annotation/issues/215) it is needed to create a new GitHub OAuth App with the following data:

- Application name: `code-annotation`
- Homepage: ~~`code-annotation.sourced.tech`~~ &rarr; `http://code-annotation.srcd.run`
- Authorization callback URL: `http://code-annotation.srcd.run/oauth-callback`

The secrets should be communicated to @src-d/infrastructure team

**Comment by mcuadros** [comment]
This application never should be exposed under `sourced.tech` domain since is an internal tool

**Comment by dpordomingo** [comment]
The proposed hostname was proposed by @rporres when I asked him for going to Prod; from my point of view, there is no necessity on having exactly that hostname, so it could be whatever @mcuadros / @rporres / @bzz purposes.
Since the staging one is `code-annotation-staging.srcd.run`
what about if the prod one would be `code-annotation-production.srcd.run`? would you like it?

**Comment by rporres** [comment]
All production cluster applications are exposed using `sourced.tech`, hence my assumption.

`code-annotation-production.srcd.run` looks fine to me.

**Comment by dpordomingo** [comment]
Since @rporres agrees too, I updated the issue desc with the proposed hostname.
If you have any other proposal @mcuadros , I have no concern about it, so feel free to use it.

**Comment by mcuadros** [comment]
I just created the OAuth, for the URL : `http://code-annotation.srcd.run/`

**Comment by dpordomingo** [comment]
keys provided by slack; thanks
