### ISSUE TITLE
Configure Google Analytics pannels for Prod and Staging after the migration 

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#241]
fix #215
previous work was done by https://github.com/src-d/code-annotation/issues/216

As required by [Prepare and deploy Production environment #215](https://github.com/src-d/code-annotation/issues/215) it is needed to use the proper `GA_TRACKING_ID` for Staging and Production

- **Prod:**
  - tracking id: `UA-109494282-2`
  - url: http://code-annotation.srcd.run
- **Staging:**
  - tracking id: `UA-115770171-1`
  - url: http://code-annotation-staging.srcd.run

Data is already being sent under that URLs and `GA_TRACKING_ID`, so the only missing thing should be to configure the Google Analytics pannels

**Comment by bzz** [comment]
Indeed, that is a useful one!

For the future - to track source{d} specific deployment configuration, it's better to use a backlog.

**Comment by gomesfernanda** [comment]
@dpordomingo I just changed _Code Annotation Tool - Production_ URL on Google Analytics. What we have now is:

**Code Annotation Tool - Production Environment**
Tracking ID: `UA-109494282-2`
URL: http://code-annotation.sourced.tech

**Code Annotation Tool - Staging Environment**
Tracking ID: `UA-115770171-1`
URL: http://code-annotation-staging.srcd.run/

We shall start seeing the traffic for Production website on GA. I'll test and let you know in case we have any issue. Thanks!

**Comment by dpordomingo** [comment]
Great @gomesfernanda 
I did some clicks in both: staging and production, you should see some of them from today at ~18:50
Feel free to reopen if you find any problem.
