### ISSUE TITLE
The application should be able to be distributed as a single binary

### ISSUE THREAD

**Issue by mcuadros** [src-d/code-annotation#34]
The application should be able to be distributed as a single binary embedding all the assets in the binary.

This allows to:
- Avoid complexity handling JavaScript dependencies.
- A mismatch between the binary and the frontend part.
- Remove the dependency of docker.
- Be more homogenous with the other src-d project and with the community

**Comment by smacker** [comment]
Please, clarify:

> Be more homogenous with the other src-d projects

https://github.com/src-d/borges
https://github.com/src-d/rovers

don't commit vendor.
