### ISSUE TITLE
Tool for Importing pairs of files

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#4]
A tool that can be called from CLI and an HTTP handler, that consumes sqlite DB with pairs of files (any schema for now, will be changed later) from FS and saves to the DDL from #2.

@EgorBu will eventually provide more details on the input schema.

**Comment by bzz** [comment]
Based on https://github.com/src-d/code-annotation/pull/10#issuecomment-359037486 - it seems that current status of this is WIP due to

> The requirements for that connection URL are basically the ability to connect to SQLite or PostgreSQL.

**Comment by carlosms** [comment]
Code in master. Any future improvements will be done in a separate issue.
