### ISSUE TITLE
Rename handler.Get(rp RequestProcessFunc) http.HandlerFunc

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#46]
Context from https://github.com/src-d/code-annotation/pull/38#issuecomment-361573410

The name `Get` for `handler.Get(rp RequestProcessFunc) http.HandlerFunc` is not clear enough
https://github.com/src-d/code-annotation/blob/master/server/handler/render.go#L17

It should be improved

**Comment by dpordomingo** [comment]
Let's consider how was the function documented:

> _Get returns an http.HandlerFunc that will serve the user request taking the serializer.Response and errors from the passed RequestProcessFunc_

And its code:
```go
func Get(rp RequestProcessFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		response, err := rp(r)
		if response == nil {
			response = serializer.NewEmptyResponse()
		}

		write(w, r, response, err)
	}
}
```

What name would you suggest?

**Comment by smacker** [comment]
How about `APIHandlerFunc`?
We use this function to serve API responses in the standard format. And it returns `HandlerFunc`.
