### ISSUE TITLE
Tool for exporting annotations

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#5]
A tool that can be called from CLI and an HTTP handler, that produces sqlite DB with pairs of files + user + answer (any schema for now, will be changed later) from an internal DB defined in #2 .

Output schema should be as simple as possible and allow to query for all answers of the single author, as well as to get all files with it's annotations.

As soon as there is something to share, we could show it to @EgorBu and iterate on his feedback (updating Design Doc).

**Comment by carlosms** [comment]
Issue blocked until we have the required output DB schema

**Comment by bzz** [comment]
Let's move forward with this and just suggest a simples schema that allows:
 - to query for all answers of the single author
 - get files with it's annotations

and iterate based on actual user feedback from there.

**Comment by carlosms** [comment]
> Let's move forward with this and just suggest a simples schema that allows:
> 
> - to query for all answers of the single author
> - get files with it's annotations

Then I think the current version works fine, a copy of the internal DB already provides those two features.

**Comment by bzz** [comment]
@carlosms sounds good, so then this is still open due to work done to support SQLight/Postgres connection URL as source argument in exporter?

**Comment by carlosms** [comment]
That's right, I just created PR #28 with code for the import tool.
The changes for the export tool will be pushed to that PR also.

**Comment by carlosms** [comment]
Code in master. Any future improvements will be done in a separate issue.
