### ISSUE TITLE
Collapsible Header

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/code-annotation#54]
To take full advantage of height in the UI for code annotation, I would like to propose for the Header element to be collapsible and revelled on :hover on top area.  

![image](https://user-images.githubusercontent.com/1746146/36783888-76c96b6a-1c75-11e8-935c-d245c87a6534.png)

**Comment by dpordomingo** [comment]
what about the progress bar?

**Comment by ricardobaeta** [comment]
@dpordomingo The collapsible element would be just the Header, not the breadcrumbs and progress bar. Something like this.

![image](https://user-images.githubusercontent.com/1746146/36783888-76c96b6a-1c75-11e8-935c-d245c87a6534.png)

**Comment by vmarkovtsev** [comment]
LGTM

**Comment by vmarkovtsev** [comment]
@ricardobaeta  Though I suggest placing this "890 lines of code" inside the code view at the upper right corner. It's OK for it to overlap with the content.

**Comment by ricardobaeta** [comment]
@vmarkovtsev Couldn't agree more :) It will be addressed for sure . Thank you ✨
