### ISSUE TITLE
Further improvements on Visual Design 

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/code-annotation#68]
Hi!

Regarding https://github.com/src-d/code-annotation/pull/53 I would like to suggest that we continue to collaborate on visual design, mainly because the footer still needs some love on height and positioning (maybe bottom-fixed). Also consider that I think that a dark theme on source code visualisation with syntax highlighting would improve the experience. I would say that the majority of people write and read code in black backgrounds. 

Also, don't forget https://github.com/src-d/code-annotation/issues/54

**Comment by dpordomingo** [comment]
@ricardobaeta Could you add a screenshot of the problem you spotted? 
(I know what are you talking about, but maybe the person that will take care of this issue won't know. :wink: )

**Comment by dpordomingo** [comment]
@ricardobaeta are the problems described here, solved by https://github.com/src-d/code-annotation/pull/65 ??
(see screenshots on PR)

**Comment by ricardobaeta** [comment]
Yes they are @dpordomingo ! Thank you for the notice :)

But then again

> Also consider that I think that a dark theme on source code visualisation with syntax highlighting would improve the experience. I would say that the majority of people write and read code in black backgrounds.
> Also, don't forget #54

**Comment by dpordomingo** [comment]
Great!!
About the dark theme, it may be quite useful if you'd edit the description and title of this issue to clarify it

**Comment by bzz** [comment]
Seems like only the dark theme is left and it is going to be addressed by https://github.com/src-d/code-annotation/issues/167

Closing this one, but please feel free to reopen if that is not the case.

In general, it is preferable to have a single issue per-improvement instead of big umbrella issue for multiple improvements together.
