### ISSUE TITLE
Implement a way to download DB exports

### ISSUE THREAD

**Issue by carlosms** [src-d/code-annotation#73]
This issue is to implement a temporary (and very basic) way to use the web interface to:
- export the data to a SQLite DB
- download that file

**Comment by bzz** [comment]
@carlosms do you think 

1) It may be worth documenting existence of the `/exports` somewhere as well, with link to schema, etc?

   So the users would be able to learn about it without deep-dive into the app code?

2) Also, as un-authorized user, I was able to access `/exports` page


<img width="1282" alt="screen shot 2018-02-14 at 4 59 58 pm" src="https://user-images.githubusercontent.com/5582506/36214123-e6f3b0bc-11a8-11e8-98a1-90c75ad46e4a.png">

**Comment by dpordomingo** [comment]
just to clarify it... 2 is not a security problem but a UX thing (because no Requester can do nothing there)

**Comment by ricardobaeta** [comment]
I'm here to help.

**Comment by carlosms** [comment]
@bzz said:

> @carlosms do you think
> 
> It may be worth documenting existence of the /exports somewhere as well, with link to schema, etc?
> So the users would be able to learn about it without deep-dive into the app code?

Yes, I'll add it to the readme. But this route should probably have a link from somewhere in the app.
Can you please clarify what do you with link to schema? Do you want to have a new file with the schema for the `assignments` table and link to it from the readme?

> Also, as un-authorized user, I was able to access /exports page

As @dpordomingo said, that is not a security problem, you can access the route but you won't be able to do or see anything. Improving this is part of #47, and I guess we'll show an empty page with a message to let you know you are not authorized.
