### ISSUE TITLE
Log overflow

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#97]
Could we avoid logs from internal things?

![image](https://user-images.githubusercontent.com/2437584/36191433-6e944582-115d-11e8-8239-7161bf5fc2af.png)

**Comment by bzz** [comment]
Indeed, we should setup default log level to WARN at least for staging deployment.

**Comment by dpordomingo** [comment]
Mmmmm... @bzz I didn't understand how your message https://github.com/src-d/code-annotation/issues/97#issuecomment-365550835 is related with the issue desc :upside_down_face:

**Comment by dpordomingo** [comment]
https://github.com/src-d/code-annotation/pull/102 is not related with this issue

**Comment by smacker** [comment]
what? PR fixes it:
> we should setup default log level to WARN at least for staging deployment

no more "overflow" of INFO logs

**Comment by dpordomingo** [comment]
Maybe the issue desc is not clear enough, but it is said 
>_Could we avoid logs from internal things?_

And a screenshot with tons of automatic access by IP

**Comment by smacker** [comment]
hahaha. I got it as we should remove `INFO` messages. And looks like @bzz also.

**Comment by bzz** [comment]
I think further discussion IRL leaked to https://github.com/src-d/code-annotation/pull/36#issuecomment-365628856

**Comment by dpordomingo** [comment]
logging specs were described by https://github.com/src-d/code-annotation/issues/123
We'll track that development in the new issue
