### ISSUE TITLE
Unhandled error in /oauth-callback 

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#98]
Considering the following [error log entry in GCP](https://console.cloud.google.com/logs/viewer?project=srcd-public&organizationId=726146880052&minLogLevel=0&expandAll=false&timestamp=2018-02-14T06%3A45%3A43.000000000Z&interval=PT1H&resource=container%2Fcluster_name%2Fstaging&logName=projects%2Fsrcd-public%2Flogs%2Fcode-annotation&dateRangeStart=2018-02-14T05%3A54%3A07.318Z&dateRangeEnd=2018-02-14T06%3A54%3A07.318Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22staging%22%0Aresource.labels.container_name%3D%22code-annotation%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.instance_id%3D%227358377787528255162%22%0Aresource.labels.pod_id%3D%22code-annotation-code-annotation-88239986-47vsm%22%0Aresource.labels.zone%3D%22europe-west1-d%22%0Aresource.labels.project_id%3D%22srcd-public%22%0Atimestamp%3D%222018-02-14T06%3A45%3A43.000000000Z%22%0AinsertId%3D%221cu51imf4cf8s8%22)
```
oauth exchange error: Post https://github.com/login/oauth/access_token: x509: 
failed to load system roots and no roots provided
```

Can we fix it, or is it a missing configuration in the server?

![image](https://user-images.githubusercontent.com/2437584/36191537-ff6965ec-115d-11e8-8f76-83c793a01b52.png)

The error was thrown by [server/service.OAuth::GetUser](https://github.com/src-d/code-annotation/blob/master/server/service/oauth.go#L94) func

**Comment by bzz** [comment]
As discussed, it has to do with missing root certificates in the container.

**Comment by dpordomingo** [comment]
solved by https://github.com/src-d/code-annotation/pull/85 https://github.com/src-d/code-annotation/pull/85/commits/bdde2907413e3b0759fd5ba7dfa552c2a9a27460
