### ISSUE TITLE
Handle internal server errors in frontend.

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#99]
There are some URLs that can return a `500` error without being caught by the frontend, so the site will show a meaningless plain error message like the following one received from [/oauth-callback](https://code-annotation-staging.srcd.run/oauth-callback) when GitHub auth fails 

The frontend should be able to catch those errors.

![image](https://user-images.githubusercontent.com/2437584/36191842-57a1981e-115f-11e8-90b4-7d834fdef2e3.png)

**Comment by bzz** [comment]
It's a bit hard to understand the current status of this issue - from the first sight, it has 2 PRs and both need to be rebased and both need to be reviewed..

Could somebody please summarize the status here please?

**Comment by smacker** [comment]
PRs description explains difference quite well. I have rebased my PR.

**Comment by dpordomingo** [comment]
Issue will be solved by original PR https://github.com/src-d/code-annotation/pull/142 and the new issue https://github.com/src-d/code-annotation/issues/201
